### PR TITLE
Enable out-of-tree builds.  autoconfigure a clock for clock_gettime. …

### PR DESCRIPTION
**Pull request by pooryorick**
… Modify

myexec to not die on stderr output.  Comment out net/ethernet.h include, which
seems to be unnecessary, and isn't available under Cygwin.

### CODE REVIEW

**Comment by bovine** [comment]
I think net/ethernet.h was necessary for the MAC Address column type? Adding a AC_CHECK_HEADER for that file might be a better option.

**Comment by resuna** [comment]
If you never use the "mac" type, this will never be referenced.

In cygwin, where are these defined?

struct ether_addr
ether_aton
ether_ntoa

**Comment by bovine** [comment]
@pooryorick Can you find out where cygwin defines those structs/typedefs?

**Comment by resuna** [comment]
@pooryorick I'd like to get this pulled in, for the clock changes, but we can't just kill net/ethernet.h ... we could merge and then undo that part of the patch if you can't provide an alternative.

**Comment by bovine** [comment]
One other user reports that no default cygwin headers include anything named "ether_*" 

So it may be necessary to make the MAC Address column type become unavailable on such platforms, or define a substitute datatype and our own conversion functions.

**Comment by resuna** [comment]
Well, I can add this to configure.in:

AC_CHECK_HEADER(net/ethernet.h,[CTABLES_CFLAGS="$CTABLES_CFLAGS
-DHAVE_NET_ETHERNET_H=1"])

And I can add this to ctable.h:

#ifdef HAVE_NET_ETHERNET_H
#include <net/ethernet.h>
#endif

That will at least avoid compilation problems if you're not using MAC
addresses.

**Comment by resuna** [comment]
Looks like the three symbols that need to be defined for mac types to work are ether_aton, ether_ntoa, and struct ether_addr.

**Comment by resuna** [comment]
According to GNUlib documentation, the ether_* functions are missing on HP-UX 11, Cygwin, mingw, MSVC 9, Interix 3.5, and BeOS.

**Comment by resuna** [comment]
Implemented an "ethers.c" for platforms that don't have the ether_* functions. Added mac-ip tests into default configuration. Please close.

**Pull request merged**
